# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "rubot/debian9"

  config.vm.box_check_update = false

  # config.vm.define "node1" do |node1|
  #   node1.vm.network "private_network", ip: "192.168.33.10"
  # end
end
