# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "rubot/debian9"

  config.vm.box_check_update = false

  config.vm.provider 'virtualbox' do |v|
    v.linked_clone = true
  end

  # config.vm.network "forwarded_port", guest: 8080, host: 80
  # config.vm.network "forwarded_port", guest: 4430, host: 443

  # config.vm.network "public_network", ip: "192.168.2.24"
  # config.vm.provision "shell",
  #   run: "always",
  #   inline: "route add default gw 192.168.2.1"

end
